name: Deploy Site to Github Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "site/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependecies
        run: |
          npm install -g lerna
          lerna bootstrap --ignore-scripts=true --npm-client=npm

      - name: Build Site
        run: lerna run build --scope=site

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: site/dist
